WEB_BlockChain/WEB_BlockChain/Models/Block.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using XSystem.Security.Cryptography;

namespace WEB_BlockChain.Models
{
    public class Block
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int? Id { get; set; }
        [Required(ErrorMessage ="Please enter your name")]
        public string Data { get; set; }
        public DateTime Created { get; set; }
        public string Hash { get; set; }
        public string PreviousHash { get; set; }
        [Required(ErrorMessage = "Please enter your user")]
        public string User { get; set; }


        public Block()
        {
            //Id = 1;
            Data = "Hello, World";
            Created = DateTime.Parse("07.02.2023 00:00:00.0");
            PreviousHash = "111111";
            User = "Admin";

            var source = GetData();
            Hash = GetHash(source);
        }

        public Block(string data, string user, Block block)
        {
            if (string.IsNullOrWhiteSpace(data))
            {
                throw new ArgumentNullException("Пустой аргумент data", nameof(data));
            }
            if (block == null)
            {
                throw new ArgumentNullException("Пустой аргумент block", nameof(block));
            }
            if (string.IsNullOrWhiteSpace(user))
            {
                throw new ArgumentNullException("Пустой аргумент user", nameof(user));
            }

            Data = data;
            User = user;
            PreviousHash = block.Hash;
            Created = DateTime.Now;
            //Id = block.Id + 1;

            var source = GetData();
            Hash = GetHash(source);
        }

        public string GetData()
        {
            string result = "";

            result += Data;
            //Нельзя использовать тк при проверке хэшей в реальном времени в Функции Check генерирется текущее время, а не время создания блока, что приводит к несовпадению хэшей
            result += Created.ToString("dd.MM.yyyy HH:mm:ss.f");
            result += PreviousHash;
            result += User;

            return result;
        }
        //Метод для функции Сheck
        public string GetData(DateTime time)
        {
            string result = "";

            result += Data;
            //Нельзя использовать тк при проверке хэшей в реальном времени в Функции Check генерирется текущее время, а не время создания блока, что приводит к несовпадению хэшей
            result += time.ToString("dd.MM.yyyy HH:mm:ss.f");
            result += PreviousHash;
            result += User;

            return result;
        }

        public string GetHash(string data)
        {
            var message = System.Text.Encoding.ASCII.GetBytes(data);
            var hashString = new SHA256Managed();
            string hex = "";

            var hashValue = hashString.ComputeHash(message);
            foreach (byte x in hashValue)
            {
                hex += String.Format("{0:x2}", x);
            }
            return hex;
        }

        public override string ToString()
        {
            return Data + " / " + Created;
        }
    }
}

WEB_BlockChain/WEB_BlockChain/Models/BlockchainContext.cs
using Microsoft.EntityFrameworkCore;

namespace WEB_BlockChain.Models
{
    public class BlockchainContext : DbContext
    {
        public BlockchainContext(DbContextOptions<BlockchainContext> options) : base(options)
        {
            Database.EnsureCreated();
        }

        public DbSet<Block> Blocks { get; set; }
    }
}

WEB_BlockChain/WEB_BlockChain/Models/Chain.cs
namespace WEB_BlockChain.Models
{
    public class Chain
    {
        public List<Block> Blocks { get; set; }

        public Block Last { get;set; }
     
   
        public bool Check()
        {
            //Транзакция считается защищенной, если ПОСЛЕ НЕЁ ЕСТЬ ХОТЯ БЫ ОДНА СЛЕДУЮЩАЯ ТРАНЗАКЦИЯ, ЕСЛИ False, ТО НУЖНО УДАЛИТЬ ПОСЛЕДНЮЮ ТРАНЗАКЦИЮ, ТК ПРИ ЕЁ ФОРМИРОВАНИИ ПРОИЗОШЕЛ ВЗЛОМ
            for (int i = 1; i < Blocks.Count; i++)
            {
                // blockchain[2].amount = 3454353; Изменение содержимого блока на фальшивые данные
                if (Blocks[i].Hash != Blocks[i].GetHash(Blocks[i].GetData(Blocks[i].Created)))
                {
                    return false;
                }
                //blockchain[2].hash = blockchain[2].getHash(); Изменение хэша блока на фальшивый хэш
                if (Blocks[i].PreviousHash != Blocks[i - 1].Hash)
                {
                    return false;
                }
                //Проверка связи (пересчёт хэша)
                if (Blocks[i].PreviousHash != Blocks[i - 1].GetHash(Blocks[i - 1].GetData(Blocks[i - 1].Created)))
                {
                    return false;
                }
            }

            return true;
        }
    }
}

WEB_BlockChain/WEB_BlockChain/Models/ErrorViewModel.cs
namespace WEB_BlockChain.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WEB_BlockChain/WEB_BlockChain/Controllers/ChainController.cs
using Microsoft.AspNetCore.Mvc;
using WEB_BlockChain.Models;

namespace WEB_BlockChain.Controllers
{
    public class ChainController : Controller
    {
        private readonly BlockchainContext _context;

        public static Chain chain = new Chain();

        public ChainController(BlockchainContext context)
        {
            _context = context;
        }

        public IActionResult View()
        {
            var blocks = _context.Blocks;
            return View(blocks);
        }

        [HttpGet]
        public ViewResult CreateBlock()
        {      
            return View("CreateBlock");
        }


        [HttpPost]
        public IActionResult CreateBlock(Block item)
        {
            if (ModelState.IsValid)
            {
                //Синхронизация с клиентом и проверка BlockChain
                chain.Blocks = _context.Blocks.ToList<Block>();

                if (chain.Blocks.Count() == 0)
                {
                    var genesisBlock = new Block();

                    chain.Blocks.Add(genesisBlock);
                    chain.Last = genesisBlock;
                    //chain.Last.Id = null;
                    _context.Blocks.Add(chain.Last);
                    _context.SaveChanges();
                }
                else
                {
                    if (chain.Check())
                    {
                        chain.Last = chain.Blocks.Last();
                    }
                    else
                    {
                        throw new Exception("Ошибка в получении блоков из базы данных");
                    }
                }




                if (item == null)
                {
                    return BadRequest();
                }
                Block block = new Block(item.Data, item.User, chain.Last);
                chain.Last = block;
                //block.Id = null;

                _context.Blocks.Add(block);
                _context.SaveChanges();

                //var blocks = _context.Blocks;
                return View("View", _context.Blocks);
            }
            else
            {
                return View("CreateBlock");
            }
            
        }
    }
}

WEB_BlockChain/WEB_BlockChain/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WEB_BlockChain.Models;

namespace WEB_BlockChain.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        
        public IActionResult Index()
        {
            return View();
        }
        
        public IActionResult About()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WEB_BlockChain/WEB_BlockChain/Views/Chain/CreateBlock.cshtml
@model WEB_BlockChain.Models.Block
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create Block</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
</head>
<body>
    <div class="text-center"><h4>Создание блока</h4></div>
    <div>
        <form asp-controller="Chain" asp-action="CreateBlock" method="post">
            <div asp-validation-summary="All"></div>
            <div class="mb-3">
                <label class="form-label" asp-for="Data">Data:</label>
                <input class="form-control" asp-for="Data" />
            </div> 
            <div class="mb-3">
                <label class="form-label" asp-for="User">User:</label>
                <input class="form-control" asp-for="User" />
            </div>   
            <div class="text-center">
                <button class="btn btn-primary" type="submit">Submit</button>
            </div>
        </form>
    </div>
</body>
</html>

WEB_BlockChain/WEB_BlockChain/Views/Chain/View.cshtml
@model IEnumerable<Block>
@{
    Layout = "_Layout";
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>All chain</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
</head>
<body class="panel-body">
    <h2>Вся цепь</h2>
    <h3>Количество блоков в цепи: @Model.Count()</h3>
    <h3>Время последней транзакции: @Model.Last().Created.ToString()</h3>
    <div>
        <p>

        </p>
    </div>
    <div  class="table-responsive">
        <table class="table table-sm">
            <thead class="table-dark ">
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col" style="width: 16.66%">Data</th>
                    <th scope="col">Created</th>
                    <th scope="col">Hash</th>
                    <th scope="col">PreviousHash</th>
                    <th scope="col">User</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var r in Model)
                {
                    <tr>
                        <th scope="row">@r.Id</th>
                        <td>@r.Data</td>
                        <td>@r.Created.ToString()</td>
                        <td>@r.Hash</td>
                        <td>@r.PreviousHash</td>
                        <td>@r.User</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <p>Click <a class="nav-link" asp-controller="Home" asp-action="Index">here</a> to see home.</p>
</body>
</html>

WEB_BlockChain/WEB_BlockChain/Views/Home/About.cshtml
@{
    ViewBag.Title = "О программе";
}

<div class="page-header">
    <h1>@ViewBag.Title Blockchain Explorer Web</h1>
</div>

<h3>Общее описание</h3>
<p>
    Blockchain Explorer Web это веб-приложение позволяющее выполнять просмотр содержимого хранилища информации на базе технологии блокчейн, а также вносить новые данные в систему.
    Блокчейн — выстроенная по определённым правилам непрерывная последовательная цепочка блоков (связный список), содержащих информацию. 
    Чаще всего копии цепочек блоков хранятся на множестве разных компьютеров независимо друг от друга.
</p>

<h3>Структура проекта</h3>
<p>
    Решение Blockchain включает в себя несколько проектов:
    <ol>
        <li>Blockchain - основная библиотека реализующая логику работы приложения;</li>
        <li>BlockchainData - библиотека реализующее работу хранилищем данных приложения;</li>
        <li>BlockchainExplorerDesktop - Windows Form приложение, позволяющее работать с локальной службой Blockchain;</li>
        <li>BlockchainExplorerDesktop - Windows Form приложение, позволяющее работать с локальной службой Blockchain;</li>
        <li>BlockchainExplorerWeb - веб-приложение, позволяющее работать со службой Blockchain расположеной в сети интернет;</li>
        <li>BlockchainService - WCF-служба для работы с системой Blockchain;</li>
        <li>BlockchainTests - модульные тесты к решению blockchain.</li>
    </ol>
</p>

<h3>Описание проекта</h3>
<p>
    Данный проект реализует основную логику работы приложения.
    Для реализации цепочки блоков используется класс Chain, который позволяет выполнять хеширование данных с помощью одного из алгоритмов хеширования. 
    На данный момент в системе используется алгоритм SHA256, но предусмотрена возможность быстрого добавления других алгоритмов.
    Для хранения информации используется MS SQL сервер, но также как и с алгоритмами хеширования, предусмотрена возможность быстрой замены хранилища данных.
    Цепочка хранит в себе набор связанных блоков. Особенностью данной реализации цепочки является то, что она хранит в себе всю необходимую системную информацию,
    такую как информацию о серверах используемых в сети, и информацию о пользователях системы. Доступ к специализированным системным записям предоставлен 
    через специальные списки, для удобного и быстрого доступа.
    Система способна как создавать новую цепочку блоков, при отсутствии внешних источников подключения, так и получать существующую цепочку из глобальной сети.
    При первом включении система постарается подключится к глобальной сети блокчейн и синхронизировать данные с ней. В дальнейшем данные будут добавляться 
    как в локальное хранилище сети, так и рассылаться по всей глобальной сети.
    Добавление данных выполняется в единую цепочку блоков с указанием типа блока. Предусмотрена возможность быстрого расширения количества типов блоков.
    Взаимодействие между службами осуществляется через запросы к API службы.
</p>
<p>
    Блок данных включает в себя следующую информацию: Версия протокола блока (пока всегда равно единице), Дату создания блока, Хеш блока, Хеш предыдущего блока,
    Информационные данные хранимые в блоке и информацию о пользователе создавшем блок. Данные представляют собой сериализованную в формате json информацию,
    добавленную пользователем в текстовом формате, либо данные о сервере блокчейн, либо сведения о пользователе. Тип блока задается с помощью специального свойства.
    Предоставляется удобный интерфейс сериализации и десериализации данных. Значимыми данными являются информация и ее тип.
    Пользователь содержит в себе логин и зашифрованный пароль пользователя, а также его права доступа. Данные о пользователе также хранятся с сериализованном виде.
</p>
<p>
    Данные хранятся при помощи MS SQL сервера. Для взаимодействия с базой данных используется ORM фреймворк EntityFramework 6. Используется подход Code First, что 
    позволяет автоматически создавать необходимое локальное хранилище данных localdb. При также возможно использование полноценного сервера. 
    Настройка производится в файле app.config. Интересной особенностью данного решения является доработка функционала ef, благодаря которой с помощью специального 
    атрибута можно задать формат возвращаемой даты и времени (utc или местное). 
    Имеется возможность получения всех блоков, добавление нового блока, или очистка всего хранилища. Для хранения данных используется кодировка UTF8.
</p>
<p>
    Desktop explorer подключается к локальной службе блокчейн с помощью сервиса и предоставляет возможность получения всех блоков, 
    просмотра содержимого конкретного блока, а также добавление новых данных в блокчейн. Взаимодействие с сервисом выполняется асинхронно, что 
    позволяет форме не зависать во время обработки информации. Web explorer предоставляет аналогичные возможности, но взаимодействует с глобальной службой
    через специально разработанные api интерфейс. Взаимодействие осуществляется с помощью get запросов. 
</p>
<p>
    Служба предоставляет пять методов для взаимодействия:
    <ol>
        <li>AddHost - запрос на добавление сервера службы блокчейн;</li>
        <li>AddUser - запрос на добавление пользователя;</li>
        <li>AddData - запрос на добавление данных;</li>
        <li>Login - запрос на авторизацию;</li>
        <li>GetChain - получение всех блоков.</li>
    </ol>
    Все запросы работаю асинхронно. Внутри службы существует единственный экземпляр цепочки блоков, предоставляющий потокобезопасный доступ. Как уже упоминалось ранее
    предоставляются два интерфейса доступа, как к службе, так и с помощью web api. Глобальная служба размещена в Azure.
</p>
<h3>Доступ к глобальной службе</h3>
<p>
    <ul>
        <li><a href="http://blockchain-dev-as.azurewebsites.net/" target="_blank">http://blockchain-dev-as.azurewebsites.net/</a> - основной адрес;</li>
        <li><a href="http://blockchain-dev-as.azurewebsites.net/BlockchainService.svc/api/GetChain/" target="_blank">http://blockchain-dev-as.azurewebsites.net/BlockchainService.svc/api/GetChain/</a> - получение всех блоков;</li>
        <li><a href="http://blockchain-dev-as.azurewebsites.net/BlockchainService.svc/api/AddData/Какие-то очень важные данные" target="_blank">http://blockchain-dev-as.azurewebsites.net/BlockchainService.svc/api/AddData/{text}</a> - добавление данных.</li>
        <!-- Не протестировано. Необходимо исправить в будущем.  <li><a href="http://blockchain-dev-as.azurewebsites.net/BlockchainService.svc/api/AddHost/192.168.1.1" target="_blank">http://blockchain-dev-as.azurewebsites.net/BlockchainService.svc/api/AddHost/{ip}</a> - добавление хоста;</li>
        <li><a href="http://blockchain-dev-as.azurewebsites.net/BlockchainService.svc/api/AddUser/@Guid.NewGuid()&qwerty&3" target="_blank">http://blockchain-dev-as.azurewebsites.net/BlockchainService.svc/api/AddUser/{login}&{password}&{role}</a> - добавление пользователя;</li>
        <li><a href="http://blockchain-dev-as.azurewebsites.net/BlockchainService.svc/api/Login/admin&admin" target="_blank">http://blockchain-dev-as.azurewebsites.net/BlockchainService.svc/api/Login/{login}&{password}</a> - авторизация пользователя.</li>-->
    </ul>

    <a href="http://blockchainexplorerweb20180131065911.azurewebsites.net" target="_blank">http://blockchainexplorerweb20180131065911.azurewebsites.net</a> - обозреватель блоков онлайн. <br />
    

    Исходный код доступен в репозитории github <a href="https://github.com/shwanoff/Blockchain" target="_blank">https://github.com/shwanoff/Blockchain</a>
</p>

WEB_BlockChain/WEB_BlockChain/Views/Home/Index.cshtml
<div class="jumbotron">
    <h1>Blockchain Explorer Web</h1>
    <p class="lead">Обозреватель глобального хранилища блоков. Позволяет просматривать блоки службы и добавлять новые данные.</p>
    <p>@Html.ActionLink("Подробнее", "About", "Home", routeValues: null, htmlAttributes: new { @class = "btn btn-primary btn-lg" })</p>
</div>

WEB_BlockChain/WEB_BlockChain/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WEB_BlockChain</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WEB_BlockChain.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WEB_BlockChain</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Chain" asp-action="View">View</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Chain" asp-action="CreateBlock">Create Block</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WEB_BlockChain - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>